# Generated by Django 3.1.7 on 2021-04-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=4000)),
                ('stars', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Package',
            },
        ),
        migrations.CreateModel(
            name='PackageShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=50)),
                ('version', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=300)),
                ('hosted', models.DateTimeField(null=True)),
                ('origin_file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shorts', to='search_engine.basefile')),
                ('package', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short', to='search_engine.package')),
            ],
        ),
    ]
