# Generated by Django 3.1.7 on 2021-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageshort',
            name='url',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
